<template>
  <section class="page-shell">
    <header class="page-header"><div><h1>日志审查</h1><p>按剧场、操作者、模块、风险和时间快速定位关键操作。</p></div><el-button @click="exportCsv">导出 CSV</el-button></header>
    <el-card shadow="never" class="filters"><el-form inline><el-form-item label="剧场"><el-select v-model="filters.theater_id" clearable style="width:180px"><el-option v-for="t in theaters" :key="t.id" :label="t.name" :value="t.id"/></el-select></el-form-item><el-form-item label="分类"><el-select v-model="filters.category" clearable style="width:130px"><el-option label="业务" value="business"/><el-option label="安全" value="security"/></el-select></el-form-item><el-form-item label="风险"><el-select v-model="filters.risk_level" clearable style="width:130px"><el-option label="普通" value="normal"/><el-option label="提醒" value="warning"/><el-option label="高风险" value="critical"/></el-select></el-form-item><el-form-item label="关键词"><el-input v-model="filters.keyword" clearable placeholder="摘要关键词"/></el-form-item><el-button type="primary" @click="load">查询</el-button><el-button @click="reset">重置</el-button></el-form></el-card>
    <el-card shadow="never"><el-table :data="rows" v-loading="loading"><el-table-column prop="occurred_at" label="时间" width="180"/><el-table-column prop="operator_name" label="操作者" width="130"/><el-table-column label="分类" width="90"><template #default="{row}"><el-tag :type="row.event_category==='security'?'warning':'primary'">{{row.event_category==='security'?'安全':'业务'}}</el-tag></template></el-table-column><el-table-column prop="module" label="模块" width="150"/><el-table-column prop="summary" label="操作摘要" min-width="260"/><el-table-column label="结果/风险" width="150"><template #default="{row}"><el-tag :type="row.result==='success'?'success':'danger'">{{row.result==='success'?'成功':'失败'}}</el-tag><el-tag v-if="row.risk_level!=='normal'" class="risk" :type="row.risk_level==='critical'?'danger':'warning'">{{row.risk_level==='critical'?'高风险':'提醒'}}</el-tag></template></el-table-column><el-table-column type="expand"><template #default="{row}"><pre>{{JSON.stringify({变更前:row.before_data,变更后:row.after_data,影响对象:row.affected_objects},null,2)}}</pre></template></el-table-column></el-table></el-card>
  </section>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";import { apiClient } from "../../api/client";import { adminApi } from "../../api/admin";import { useAuthStore } from "../../auth/store";
const auth=useAuthStore(), theaters=ref<{id:number;name:string}[]>([]), rows=ref<any[]>([]), loading=ref(false);const filters=reactive<{theater_id?:number;category?:string;risk_level?:string;keyword:string}>({keyword:""});
function query(){const q=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v!==undefined&&v!=="")q.set(k,String(v))});return q.toString()}
async function load(){loading.value=true;try{rows.value=await apiClient.request(`/admin/audit-logs?${query()}`,{token:auth.token})}finally{loading.value=false}}
function reset(){Object.assign(filters,{theater_id:undefined,category:undefined,risk_level:undefined,keyword:""});void load()}
async function exportCsv(){const response=await fetch(`http://localhost:7004/admin/audit-logs/export?${query()}`,{headers:{Authorization:`Bearer ${auth.token}`}});const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="审计日志.csv";a.click();URL.revokeObjectURL(url)}
onMounted(async()=>{theaters.value=await adminApi.getTheaters(auth.token!);await load()});
</script>
<style scoped>.page-shell{display:grid;gap:20px}.page-header{display:flex;justify-content:space-between;align-items:flex-end}.page-header h1{margin:0;font-size:30px}.page-header p{margin:8px 0 0;color:var(--text-secondary)}.filters :deep(.el-form-item){margin-bottom:0}.risk{margin-left:6px}pre{white-space:pre-wrap;color:var(--text-secondary);font-size:13px}</style>
